### PR TITLE
Fix justification for abducible predicates

### PR DESCRIPTION
**Pull request by eshelyaron**
This is a followup for #3 

The first commit makes sure we use a more concise format for abducibles also in the output of the `scasp` CLI tool (i.e. the main.pl module), both with and without the `--human` flag.

### CODE REVIEW

**Comment by JanWielemaker** [comment]
Thanks.    When I saw this, it also made me think about the original tree as composed in (I think) stack.pl.   Wouldn't it be better to get rid of the abducible stuff already there?   There is nothing interesting inside.    Name of the node is a bit tricky.  `abduced(p(1))`?

**Comment by eshelyaron** [comment]
>  Wouldn't it be better to get rid of the abducible stuff already there? There is nothing interesting inside. Name of the node is a bit tricky. abduced(p(1))?

Yes that sounds good, see my last commit (https://github.com/JanWielemaker/sCASP/pull/4/commits/ea2ba6f307bb8e58c29d80a1168086e6b7394330) taking this approach.
Note that this is a changes the justification tree in its representation as a Prolog term which is used by the test suite, so I needed to adjust the "excepted" justification tree for the `abdbirds` test accordingly.

**Comment by JanWielemaker** [comment]
Thanks.    Note that `test/test_scasp.pl` contains a description on how to update the test data (near main/1).

**Comment by eshelyaron** [comment]
Thanks, `swipl test/test_scasp.pl -- --overwrite test/all_programs/sasp/abdbirds.pl` seems to do the trick, I'll commit the `.pass` file it produced

**Comment by JanWielemaker** [comment]
Thanks.   Seems we can still do better though.   Am I right in seeing always the same pattern:

```
scasp --tree test/all_programs/sasp/abdbirds.pl
% Query
?- not flies(tweety).
% ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
%                                                   Answer 1 (0.000 sec)                                                    
% ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
% Justification
   query ←
      not flies(tweety) ←
         bird(tweety) ∧
         ab(tweety) ←
            chs(ab(tweety)) ∧
            abduced(ab(tweety)).
% Model
{ ab(tweety),         bird(tweety),       not flies(tweety)
}
% No bindings
true ? 
```

For the abducible we see always (I think, please verify) this pattern.   If that is true we can just as well state `abduced(P)`, no? 

```
      P ←
            chs(P) ∧
            abduced(P).
```

If you agree, please make a new PR.   This one is closed.

**Comment by eshelyaron** [comment]
> Thanks. Seems we can still do better though
> ...
> If you agree, please make a new PR. This one is closed.

Thanks, you are right about the justification pattern for abducibles and I agree we can do better, see #5.

**Pull request merged**
