### PR TITLE
ENHANCED: More concise justification for abducible predicates

### PR DESCRIPTION
**Pull request by eshelyaron**
This PR implements another improvement to the justification of abducible predicates following @JanWielemaker's suggestion from 
https://github.com/JanWielemaker/sCASP/pull/4#issuecomment-1162841582

This gives us (with the rock-paper-scissors example):
```
   The winner of the_final_round is john, because
      by abduction we conclude that john played in the_final_round, and
      by abduction we conclude that A played in the_final_round, and
      by abduction we conclude that john threw rock, and
      by abduction we conclude that A threw scissors, and
      rock beats scissors
```

Instead of:
```
   The winner of the_final_round is john, because
      john played in the_final_round, because
         it is assumed that john played in the_final_round, and
         by abduction we conclude that john played in the_final_round
      A played in the_final_round, because
         it is assumed that A played in the_final_round, and
         by abduction we conclude that A played in the_final_round
      john threw rock, because
         it is assumed that john threw rock, and
         by abduction we conclude that john threw rock
      A threw scissors, because
         it is assumed that A threw scissors, and
         by abduction we conclude that A threw scissors
      rock beats scissors
```

### CODE REVIEW

**Comment by JanWielemaker** [comment]
Nice and short :smile:

**Comment by Gauntlet173** [comment]
Can I ask why we reduce it to the "by abduction we conclude" line instead of the "it is assumed" line? I don't know if they are meaningfully different, or ever appear separate from one another, and the latter seems more intuitively readable.

**Comment by JanWielemaker** [comment]
Good question.   The first observation is that the whole tree that is created below the abducible carries no information, so collapsing it seems a good idea.   Agree?   I think it also makes sense to distinguish the even loop introduced by `#abduciple P` from arbitrary even loops that result from user code.    That, of course, is less evident.

To me, referring to the `#abducible P` in the explanation is added value.   What is the downside?

**Comment by Gauntlet173** [comment]
I am not aware of any value from leaving the entire tree. I agree with collapsing, absolutely.

There are also reasons to be able to distinguish between different kinds of even loops, but I think there may also be reasons to be able to distinguish between abducibility statements that are included in the code to represent different things. Some represent ontological certainties (a person is either alive or dead), others represent acceptable presumptions (presume that people are alive), and other represent uncertainties (I don't know if schroedinger's cat is alive or dead). So I can see reasons to want to distinguish all kinds of things. So I can imagine reasons to be able to distinguish between them in the explanations. A user interview should treat a factual uncertainty differently from an acceptable presumption, for example.

I'm not sure if that explains or justifies the choice to use the word "abducible" to describe the output to the user, because it feels to me like it is harder to read, and it is not really a description of the model, but a description of the code that generated the model.

I could be wrong about this, but my understanding is that we are using the word "abducible" in contrast to "deducible". But inside a single model, inside an explanation, there is only deduction. The model was generated by an abductive process, and because of abduction another model with the opposite possibility was also generated, and perhaps discarded, but there is no abduction happening in the explanation.

I also worry slightly about changing the structure of the explanation to replace the bare fact with the assumed version of the fact, instead of providing the assumption as a sub-justification. I worry about whether that is providing potentially the same information in two different ways depending on whether it was assumed or not, which in certain circumstances may not be relevant (such as when all of the abducibility is due to acceptable presumpsions).  That concern may be misplaced, but I feel like it would go like this:

* conclusion holds, because
  * condition holds, because
    * condition holds is assumed

Then if the condition is known as a fact, you just don't include the third line, so the format of the condition is always the same.

Assuming is a word that means something to normal people, and that seems like an accurate description of what's happening within the explanation.

But honestly, the wording is probably not critical, so much as the semantic consistency of the justification tree, so that users have all the information they need about each model. The specific words used in the NLG are secondary, to me.

Let me know if that helps at all, or if I am only confusing things. :)

**Pull request merged**
